#!/bin/sh
mkdir -p ~/dl ~/.cache/zsh
git clone https://github.com/71zenith/dotfiles.git ~/.config
mkdir ~/.local
git clone https://github.com/71zenith/scripts.git ~/.local/bin/
cd ~/.config
git remote set-url origin git@github.com:71zenith/dotfiles
cd ~/.local/bin/
git remote set-url origin git@github.com:71zenith/scripts
