#!/bin/bash

ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo -e "keycode 1 = Caps_Lock\nkeycode 58 = Escape" > /usr/share/kbd/keymaps/caps-esc.map
echo -e "FONT=ter-122n\nKEYMAP=caps-esc" > /etc/vconsole.conf
echo "kujira" >> /etc/hostname
echo -e "127.0.0.1    localhost\n::1          localhost\n127.0.1.1    kujira" >> /etc/hosts
echo "permit nopass :wheel" >> /etc/doas.conf
ln -sfT /bin/doas /bin/sudo
bootctl install
echo -e "default arch.conf\ntimeout 10" > /boot/loader/loader.conf
echo -e "title   Arch Linux\nlinux   /vmlinuz-linux-lts\ninitrd  /initramfs-linux-lts.img\noptions root=\"LABEL=Arch\" resume=\"LABEL=Swap\" rw" > /boot/loader/entries/arch.conf
echo "ZDOTDIR=/home/zen/.config/zsh" >> /etc/environment
systemctl enable NetworkManager
useradd -m zen -G wheel,audio,video
passwd
passwd zen
pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
pacman-key --lsign-key FBA220DFC880C036
pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
sed -e 's/CheckSpace/#CheckSpace/' -e 's/#ParallelDownloads\ =\ 5/ParallelDownloads = 10\nILoveCandy/' -e 's/#Color/Color/' -e 's/#VerbosePkgLists/VerbosePkgLists/' -e '$a [chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist' -i /etc/pacman.conf
pacman -Sy --noconfirm lf librewolf nerd-fonts-jetbrains-mono
sed -e 's/^HOOKS.*/HOOKS=(base udev autodetect keyboard modconf block filesystems resume fsck)/' -e 's/vim.*/vim:ft=sh/' -i /etc/mkinitcpio.conf
mkinitcpio -p linux-lts
curl -L https://github.com/71zenith/archinstall/raw/master/xorg.conf > /etc/X11/xorg.conf
curl -L https://github.com/71zenith/archinstall/raw/master/postpost > /home/zen/postpost
su -c "sh /home/zen/postpost" zen
chsh zen -s /bin/zsh
rm -rf /home/zen/{.bash_history,.bash_profile,.bash_logout,.bashrc,postpost}
