#!/bin/sh
setfont ter-122n

sed -e 's/CheckSpace/#CheckSpace/' -e 's/#Color/Color/' -e 's/#VerbosePkgLists/VerbosePkgLists/' -i /etc/pacman.conf

reflector --country China,India --latest 10 --sort rate --save /etc/pacman.d/mirrorlist

mkfs.fat -F32 /dev/sdb1
mkswap /dev/sdb2 -L "Swap"
yes | mkfs.ext4 /dev/sdb3 -L "Arch"
yes | mkfs.ext4 /dev/sdb4
mount /dev/sdb3 /mnt
mkdir /mnt/{boot,home}
mount /dev/sdb1 /mnt/boot
mount /dev/sdb4 /mnt/home
swapon /dev/sdb2

pacstrap /mnt base bspwm git linux-lts man neovim networkmanager nvidia-lts opendoas playerctl pulseaudio pulseaudio-alsa pulsemixer openssh sxhkd terminus-font adobe-source-han-sans-jp-fonts xorg-server xorg-xinit xorg-xprop xorg-xset xorg-xsetroot xwallpaper pop-gtk-theme pop-icon-theme xsel mpv zsh calibre picom fcitx fcitx-mozc dunst rofi zoxide starship

# generating the fstab file
genfstab -U /mnt >> /mnt/etc/fstab

cp -f /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist

curl -L https://github.com/71zenith/archinstall/raw/master/post > /mnt/post

arch-chroot /mnt sh post
rm -rf /mnt/post
